### ISSUE TITLE
Ошибка конвертации объявлений для обновления

### ISSUE THREAD

**Issue by SonicGD** [sitkoru/yandex-direct-api#122]
При выполнении метода toUpdateEntities у AdsService появляется ошибка

```
JSON property "Items" is an array of type "string" but contained a value of type "object"
```

```
#0 /vendor/netresearch/jsonmapper/src/JsonMapper.php(282): JsonMapper->mapArray(Array, Array, 'string', 'Items')
#1 /vendor/netresearch/jsonmapper/src/JsonMapper.php(295): JsonMapper->map(Object(stdClass), Object(directapi\common\containers\ArrayOfString))
#2 /vendor/netresearch/jsonmapper/src/JsonMapper.php(295): JsonMapper->map(Object(stdClass), Object(directapi\services\ads\models\CpmBannerAdBuilderAdUpdate))
#3 /vendor/sitkoru/yandex-direct-api/src/services/BaseService.php(440): JsonMapper->map(Object(stdClass), Object(directapi\services\ads\models\AdUpdateItem))
#4 /vendor/sitkoru/yandex-direct-api/src/services/ads/AdsService.php(246): directapi\services\BaseService->convertClass(Array, 'directapi\\servi...')
#5 /vendor/sitkoru/context-cache/src/direct/DirectAdsProvider.php(239): directapi\services\ads\AdsService->toUpdateEntities(Array)
```

**Comment by SonicGD** [comment]
Проблема в поле `TrackingPixels` у `CpmBannerAdBuilderAd`. При чтении объявлений Яндекс возвращает следующую структуру:

```
"TrackingPixels": { /* TrackingPixelGetArray */
          "Items": [{ /* TrackingPixelGetItem */
            "TrackingPixel": (string), /* required */
            "Provider": (string) /* required */
          }, ... ] /* required */
        }, /* nillable */
```

Но при этом для добавления/изменения хочет вот так:

```
 "TrackingPixels": { /* ArrayOfString */
          "Items": [(string), ... ] /* required */
        }, /* nillable */
```

В итоге маппинг падает.
